PsychopatzCore = PsychopatzCore or {}
PsychopatzCore.Inventory = PsychopatzCore.Inventory or {}

local C = {}

C.REGISTRY_SCHEMA = 1
C.RECORD_SCHEMA = 1
C.VIRTUAL_SCHEMA = 1
C.NETWORK_SCHEMA = 1

C.TYPE_ID = 1
C.QUANTITY = 2
C.FLAGS = 3
C.CODEC_ID = 4
C.STATE = 5
C.UNIT_WEIGHT = 6
C.STACK_DISCRIMINATOR = 7

C.FLAG_CONDITION = 1
C.FLAG_USED_DELTA = 2
C.FLAG_FAVORITE = 4
C.FLAG_CUSTOM_NAME = 8
C.FLAG_MOD_DATA = 16
C.FLAG_FOOD = 32
C.FLAG_AMMO = 64
C.FLAG_CLOTHING = 128
C.FLAG_CONTAINER = 256
C.FLAG_CUSTOM_WEIGHT = 512
C.KNOWN_FLAGS = 1023

C.CODEC_GENERIC = 1
C.CODEC_FOOD = 2
C.CODEC_DRAINABLE = 3
C.CODEC_WEAPON = 4
C.CODEC_CLOTHING = 5
C.CODEC_CONTAINER = 6
C.CODEC_FALLBACK = 255

PsychopatzCore.Inventory.Constants = C
return C
